/* Generated by Payload (create-payload-app), then extended with the theme attribute
   below. Payload regenerates only ./admin/importMap.js, never this file. */
import config from '@payload-config'
import '@payloadcms/next/css'
import type { ServerFunctionClient } from 'payload'
import { handleServerFunctions, RootLayout } from '@payloadcms/next/layouts'
import { cookies } from 'next/headers'
import React from 'react'

import { THEME_AUTO_ATTRIBUTE, THEME_COOKIE } from '@/lib/admin-theme'

import { importMap } from './admin/importMap.js'
import './custom.scss'

type Args = {
  children: React.ReactNode
}

const serverFunction: ServerFunctionClient = async function (args) {
  'use server'
  return handleServerFunctions({
    ...args,
    config,
    importMap,
  })
}

/**
 * Marks <html> with data-theme-auto while the owner has not chosen a theme, so the page
 * follows the device setting before Payload's JavaScript takes over (see custom.scss).
 */
async function themeHtmlProps(): Promise<React.HtmlHTMLAttributes<HTMLHtmlElement>> {
  const choice = (await cookies()).get(THEME_COOKIE)?.value
  if (choice === 'dark' || choice === 'light') {
    return {}
  }
  return { [THEME_AUTO_ATTRIBUTE]: '' } as React.HtmlHTMLAttributes<HTMLHtmlElement>
}

const Layout = async ({ children }: Args) => (
  <RootLayout
    config={config}
    htmlProps={await themeHtmlProps()}
    importMap={importMap}
    serverFunction={serverFunction}
  >
    {children}
  </RootLayout>
)

export default Layout
